ASSETS = ("SPY", "TIP", "IEF", "BIL")
LEVERAGED_ASSETS = ("SSO",)
CLASSIC_OFFENSIVE_ASSETS = ("SPY", "IWM", "PDBC", "TLT", "VEA", "VNQ", "VWO")
CLASSIC_DEFENSIVE_ASSETS = ("IEF", "BIL")
CLASSIC_DATA_ASSETS = ("TIP", *CLASSIC_DEFENSIVE_ASSETS, *CLASSIC_OFFENSIVE_ASSETS)
STRATEGY_NAME = "HAA-Simple"
MOMENTUM_LOOKBACKS = (1, 3, 6, 12)
DEFAULT_TAX_RATE = 0.25
